apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: py-4454tt-utd
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: py-4454tt-utd 
  name: py-4454tt-utd
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: py-4454tt-utd 
